### ISSUE TITLE
Error: Fixable rules must set the `meta.fixable` property to "code" or "whitespace"

### ISSUE THREAD

**Issue by codeuniquely** [wisniewski94/eslint-plugin-no-comments#3]
Oops! Something went wrong! :(

ESLint: 8.19.0

Error: Fixable rules must set the `meta.fixable` property to "code" or "whitespace".
Occurred while linting /Users/Projects/test/src/app/main.ts:1
Rule: "no-comments/disallowComments"
    at Object.report (/Users/Projects/test/node_modules/eslint/lib/linter/linter.js:1088:35)
    at processComment (/Users/Projects/test/node_modules/eslint-plugin-no-comments/index.js:9:21)
    at Array.forEach (<anonymous>)
    at Program (/Users/steve/Projects/test/node_modules/eslint-plugin-no-comments/index.js:22:22)
    at ruleErrorHandler (/Users/Projects/test/node_modules/eslint/lib/linter/linter.js:1114:28)
    at /Users/Projects/test/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/Projects/test/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/Projects/test/node_modules/eslint/lib/linter/node-event-generator.js:297:26)
    at NodeEventGenerator.applySelectors (/Users/Projects/test/node_modules/eslint/lib/linter/node-event-generator.js:326:22)

**Comment by wisniewski94** [comment]
I think the eslint update could cause it. I will fix the code and docs this week. Thanks for reporting 👍

**Comment by wisniewski94** [comment]
So I have come back to this issue and I cannot reproduce it however, I added fixable property anyway. Let me know if the issue still occurs
